sudo: true
language: cpp
compiler: gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - ./install_oclint.sh

install: sudo apt-get install -qq g++-5

addons: 
  apt: 
    packages: libboost-all-dev

script: 
  - qmake
  - make 
  - ./travis_qmake_gcc_cpp11_boost_oclint
  - ./do_oclint.sh
